// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutoYa.Test.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PropietariosServiceTestsFeature : object, Xunit.IClassFixture<PropietariosServiceTestsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PropietariosServiceTests.feature"
#line hidden
        
        public PropietariosServiceTestsFeature(PropietariosServiceTestsFeature.FixtureData fixtureData, AutoYa_Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "PropietariosServiceTests", "As a propietario\r\nI want to add my information to AutoYa\'s system\r\nIn order to ma" +
                    "ke it available for applications.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
    #line hidden
#line 7
        testRunner.Given("the Endpoint http://localhost:5267/api/v1/propietarios is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add propietario with unique Email")]
        [Xunit.TraitAttribute("FeatureTitle", "PropietariosServiceTests")]
        [Xunit.TraitAttribute("Description", "Add propietario with unique Email")]
        [Xunit.TraitAttribute("Category", "propietario-adding")]
        public virtual void AddPropietarioWithUniqueEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "propietario-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add propietario with unique Email", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 10
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nombres",
                            "Apellidos",
                            "FechaNacimiento",
                            "Telefono",
                            "Correo",
                            "Contrasenia"});
                table7.AddRow(new string[] {
                            "Erick",
                            "Urbi",
                            "2023-11-18T16:07:53.406Z",
                            "123456789",
                            "erick@hotmail.com",
                            "password"});
#line 12
        testRunner.When("a Post Request for propietario is sent", ((string)(null)), table7, "When ");
#line hidden
#line 16
        testRunner.Then("a Response for propietario is received with Status 200", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Nombres",
                            "Apellidos",
                            "FechaNacimiento",
                            "Telefono",
                            "Correo",
                            "Contrasenia"});
                table8.AddRow(new string[] {
                            "1",
                            "Erick",
                            "Urbi",
                            "2023-11-18T16:07:53.406Z",
                            "123456789",
                            "erick@hotmail.com",
                            "password"});
#line 18
        testRunner.And("an propietario Resource is included in Response body", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add propietario with existing Email")]
        [Xunit.TraitAttribute("FeatureTitle", "PropietariosServiceTests")]
        [Xunit.TraitAttribute("Description", "Add propietario with existing Email")]
        [Xunit.TraitAttribute("Category", "propietario-adding")]
        public virtual void AddPropietarioWithExistingEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "propietario-adding"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add propietario with existing Email", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 23
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Nombres",
                            "Apellidos",
                            "FechaNacimiento",
                            "Telefono",
                            "Correo",
                            "Contrasenia"});
                table9.AddRow(new string[] {
                            "1",
                            "Gabriel",
                            "Alvarez",
                            "2023-11-18T16:07:53.406Z",
                            "987654321",
                            "gabriel@hotmail.com",
                            "password2"});
#line 25
        testRunner.Given("An propietario is already stored", ((string)(null)), table9, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nombres",
                            "Apellidos",
                            "FechaNacimiento",
                            "Telefono",
                            "Correo",
                            "Contrasenia"});
                table10.AddRow(new string[] {
                            "Gabriel",
                            "Alvarez",
                            "2023-11-18T16:07:53.406Z",
                            "987654321",
                            "gabriel@hotmail.com",
                            "password2"});
#line 29
        testRunner.When("a Post Request for propietario is sent", ((string)(null)), table10, "When ");
#line hidden
#line 33
        testRunner.Then("a Response for propietario is received with Status 400", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 35
        testRunner.And("An Error Message for propietario is returned with value \"Ya existe un propietario" +
                        " registrado con el correo electrónico gabriel@hotmail.com.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PropietariosServiceTestsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PropietariosServiceTestsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
